# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbbd379c093fa61f76693a1b2cdc71162dfe88b519d1b3a0006936f5525ffc0964ebbce4b9bb409117f7a6041dbc2c8075893e6893bd49c21a9702e61fccfa45

test:
  secret_key_base: 208758b2fa452bc3d541e096bcb93507af396dbc64b1176fbefe942eb5329bd6e7df5a10e8b1c208049cab2a5b6c4c760cc1b8f570e5452a15c78b14c01d389a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
